name: 🐧 OpenMP

on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref }}-ubuntu
  cancel-in-progress: true

jobs:
  build_cxxminimal:
    name: GCC Minimal w/o MPI
    runs-on: ubuntu-20.04
    env: {CXXFLAGS: "-Werror"}
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        .github/workflows/dependencies/gcc.sh
    - name: build WarpX
      run: |
        cmake -S . -B build_3D         \
          -DCMAKE_VERBOSE_MAKEFILE=ON  \
          -DWarpX_MPI=OFF              \
          -DWarpX_QED=OFF
        cmake --build build_3D -j 2
        cmake -S . -B build_3D_EM      \
          -DCMAKE_VERBOSE_MAKEFILE=ON  \
          -DWarpX_MPI=OFF              \
          -DWarpX_QED=OFF              \
          -DWarpX_MAG_LLG=OFF
        cmake --build build_3D_EM -j 2
        cmake -S . -B build_RZ         \
          -DCMAKE_VERBOSE_MAKEFILE=ON  \
          -DWarpX_DIMS=RZ              \
          -DWarpX_MPI=OFF              \
          -DWarpX_QED=OFF
        cmake --build build_RZ -j 2

  build_pyfull:
    name: Clang pywarpx
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        .github/workflows/dependencies/pyfull.sh
    - name: build WarpX
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        export WarpX_MPI=ON
        export WarpX_OPENPMD=ON
        export WarpX_PSATD=ON
        export WarpX_QED_TABLE_GEN=ON
        export CC=$(which clang)
        export CXX=$(which clang++)
        export CXXFLAGS="-Werror -Wno-error=pass-failed"
        python3 -m pip install -v .
